name: pakbmobile
description: A new Flutter project.

publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  csv: ^5.0.0
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  provider: ^6.1.2
  http: ^0.13.5 
  flutter_lints: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/laptop.csv
    - assets/logo.png
